# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 561, 641))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.genderlabel = QtWidgets.QLabel(self.page)
        self.genderlabel.setGeometry(QtCore.QRect(130, 300, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.genderlabel.setFont(font)
        self.genderlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.genderlabel.setObjectName("genderlabel")
        self.connectButton = QtWidgets.QPushButton(self.page)
        self.connectButton.setEnabled(False)
        self.connectButton.setGeometry(QtCore.QRect(220, 560, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.connectButton.setFont(font)
        self.connectButton.setObjectName("connectButton")
        self.girlButton = QtWidgets.QPushButton(self.page)
        self.girlButton.setGeometry(QtCore.QRect(400, 40, 120, 120))
        self.girlButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/girl_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.girlButton.setIcon(icon)
        self.girlButton.setIconSize(QtCore.QSize(120, 120))
        self.girlButton.setCheckable(False)
        self.girlButton.setObjectName("girlButton")
        self.boyButton = QtWidgets.QPushButton(self.page)
        self.boyButton.setGeometry(QtCore.QRect(50, 40, 120, 120))
        self.boyButton.setStyleSheet("")
        self.boyButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/boy_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boyButton.setIcon(icon1)
        self.boyButton.setIconSize(QtCore.QSize(120, 120))
        self.boyButton.setCheckable(False)
        self.boyButton.setChecked(False)
        self.boyButton.setObjectName("boyButton")
        self.over18Mode = QtWidgets.QCheckBox(self.page)
        self.over18Mode.setGeometry(QtCore.QRect(130, 370, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.over18Mode.setFont(font)
        self.over18Mode.setObjectName("over18Mode")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.backButton = QtWidgets.QPushButton(self.page_2)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 30, 30))
        self.backButton.setObjectName("backButton")
        self.chatWidget = QtWidgets.QWidget(self.page_2)
        self.chatWidget.setEnabled(True)
        self.chatWidget.setGeometry(QtCore.QRect(20, 40, 531, 591))
        self.chatWidget.setObjectName("chatWidget")
        self.genderPicClient = QtWidgets.QLabel(self.chatWidget)
        self.genderPicClient.setGeometry(QtCore.QRect(10, 170, 61, 71))
        self.genderPicClient.setText("")
        self.genderPicClient.setPixmap(QtGui.QPixmap(":/newPrefix/boy.png"))
        self.genderPicClient.setObjectName("genderPicClient")
        self.genderPicUser = QtWidgets.QLabel(self.chatWidget)
        self.genderPicUser.setGeometry(QtCore.QRect(430, 390, 61, 71))
        self.genderPicUser.setText("")
        self.genderPicUser.setPixmap(QtGui.QPixmap(":/newPrefix/boy.png"))
        self.genderPicUser.setObjectName("genderPicUser")
        self.chatBubble = QtWidgets.QLabel(self.chatWidget)
        self.chatBubble.setGeometry(QtCore.QRect(10, 290, 421, 181))
        self.chatBubble.setText("")
        self.chatBubble.setPixmap(QtGui.QPixmap(":/newPrefix/talking.png"))
        self.chatBubble.setScaledContents(True)
        self.chatBubble.setObjectName("chatBubble")
        self.chatBubble_2 = QtWidgets.QLabel(self.chatWidget)
        self.chatBubble_2.setGeometry(QtCore.QRect(90, -60, 431, 261))
        self.chatBubble_2.setText("")
        self.chatBubble_2.setPixmap(QtGui.QPixmap(":/newPrefix/talking_2.png"))
        self.chatBubble_2.setScaledContents(True)
        self.chatBubble_2.setObjectName("chatBubble_2")
        self.userText = QtWidgets.QTextBrowser(self.chatWidget)
        self.userText.setGeometry(QtCore.QRect(105, 330, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userText.setFont(font)
        self.userText.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.userText.setStyleSheet("border-color: rgba(0, 0, 0, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border-width : 1.2px;\n"
"border-style:inset;\n"
"")
        self.userText.setObjectName("userText")
        self.sendButton = QtWidgets.QPushButton(self.chatWidget)
        self.sendButton.setGeometry(QtCore.QRect(440, 510, 80, 60))
        self.sendButton.setObjectName("sendButton")
        self.textArea = QtWidgets.QTextEdit(self.chatWidget)
        self.textArea.setGeometry(QtCore.QRect(20, 510, 401, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textArea.setFont(font)
        self.textArea.setObjectName("textArea")
        self.userName_2 = QtWidgets.QLabel(self.chatWidget)
        self.userName_2.setGeometry(QtCore.QRect(420, 360, 81, 31))
        self.userName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.userName_2.setWordWrap(True)
        self.userName_2.setObjectName("userName_2")
        self.clientName = QtWidgets.QLabel(self.chatWidget)
        self.clientName.setGeometry(QtCore.QRect(0, 140, 81, 31))
        self.clientName.setAlignment(QtCore.Qt.AlignCenter)
        self.clientName.setWordWrap(True)
        self.clientName.setObjectName("clientName")
        self.clientText = QtWidgets.QLabel(self.chatWidget)
        self.clientText.setGeometry(QtCore.QRect(180, 50, 251, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clientText.setFont(font)
        self.clientText.setText("")
        self.clientText.setTextFormat(QtCore.Qt.AutoText)
        self.clientText.setScaledContents(False)
        self.clientText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.clientText.setWordWrap(True)
        self.clientText.setObjectName("clientText")
        self.waitingWidget = QtWidgets.QWidget(self.page_2)
        self.waitingWidget.setGeometry(QtCore.QRect(10, 30, 551, 601))
        self.waitingWidget.setObjectName("waitingWidget")
        self.waitingText = QtWidgets.QLabel(self.waitingWidget)
        self.waitingText.setGeometry(QtCore.QRect(50, 190, 441, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.waitingText.setFont(font)
        self.waitingText.setAlignment(QtCore.Qt.AlignCenter)
        self.waitingText.setObjectName("waitingText")
        self.reconnectButton = QtWidgets.QPushButton(self.waitingWidget)
        self.reconnectButton.setGeometry(QtCore.QRect(200, 460, 120, 60))
        self.reconnectButton.setObjectName("reconnectButton")
        self.stackedWidget.addWidget(self.page_2)
        self.errorMessage = QtWidgets.QLabel(self.centralwidget)
        self.errorMessage.setGeometry(QtCore.QRect(80, 475, 441, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.errorMessage.setFont(font)
        self.errorMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.errorMessage.setObjectName("errorMessage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.backButton.clicked.connect(MainWindow.exitClicked)
        self.sendButton.clicked.connect(MainWindow.sendClicked)
        self.boyButton.clicked.connect(MainWindow.boyClicked)
        self.girlButton.clicked.connect(MainWindow.girlClicked)
        self.connectButton.clicked.connect(MainWindow.connectClicked)
        self.reconnectButton.clicked.connect(MainWindow.connectClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChatRoom"))
        self.genderlabel.setText(_translate("MainWindow", "請選擇性別開始聊天"))
        self.connectButton.setText(_translate("MainWindow", "開始聊天"))
        self.over18Mode.setText(_translate("MainWindow", "18+ Mode"))
        self.backButton.setText(_translate("MainWindow", "<-"))
        self.userText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.sendButton.setText(_translate("MainWindow", "傳送"))
        self.textArea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p></body></html>"))
        self.userName_2.setText(_translate("MainWindow", "你"))
        self.clientName.setText(_translate("MainWindow", "對方"))
        self.waitingText.setText(_translate("MainWindow", "等待其他人加入中...."))
        self.reconnectButton.setText(_translate("MainWindow", "重新連線"))
        self.errorMessage.setText(_translate("MainWindow", "無法連接伺服器請稍後再試一次"))

import source_rc
